### ISSUE TITLE
Licence information missing

### ISSUE THREAD

**Issue by PeteLawler** [MiguelAngelLV/gas_station_spain#12]
I'd like to fork your repository to get it to work with one of my country's similar systems. I'd been thinking of doing something like this for some time, but as soon as I found yours I though a fork may be possible with the remote possibility of eventually a merge so as to start a global fuel price component.
Anyway, my initial problem is that you've not provided any Licence information. Before I can fork and do things to the code, I'd like to know (a) if source is available to fork, and (b) which licence applies.
Apologies for my usage of English. My Spanish is very rusty as it's been over 20 years since I visited Spain, and I don't enjoy using Google Translate for Issue Submission. I hope that's OK.

**Comment by MiguelAngelLV** [comment]
Added license. It is MIT ;)

**Comment by PeteLawler** [comment]
Thanks for replying, and super quick.
