### ISSUE TITLE
Puntos de recarga

### ISSUE THREAD

**Issue by sergey08** [MiguelAngelLV/gas_station_spain#13]
Hola,

Me encanta este desarrollo y lo bien que funciona.

Si quieres añadir puntos de carga, he encontrado este XML de la DGT que se actualiza a menudo

https://infocar.dgt.es/datex2/v3/miterd/EnergyInfrastructureTablePublication/electrolineras.xml

Lo mismo te vale para hacer algo similar

Saludos

**Comment by MiguelAngelLV** [comment]
Un XML con todo a pegote, como le gusta a nuestro gobierno...

El caso es que no sé muy bien qué uso darle, porque es más bien para  buscar cuales hay en una zona, no para tener una «controlada»

**Comment by sergey08** [comment]
A ver si con suerte mas adeltante viene con precios el KWh y se puede hacer algo similar a las gasolineras

**Comment by MiguelAngelLV** [comment]
Claro, si tuviese los precios o algo, pues sería interesante estar actualizándose, pero ahora mismo, que solo te indica dónde están, pues... Tendrías que saber primero dónde están para agregarlos, y después pues poca utilidad tiene.
