### ISSUE TITLE
No se corresponde el precio con lo indicado en la web

### ISSUE THREAD

**Issue by ppnacho** [MiguelAngelLV/gas_station_spain#16]
El precio que figura en la web del ministerio no coincide con el mostrado por el sensor a fecha de hoy marca 10 centimos inferior a la pagina del ministerio.

**Comment by MiguelAngelLV** [comment]
¿Sigue pasando o ha sido un error puntual?

**Comment by ppnacho** [comment]
Hola,

Pongo unas capturas sacadas ahora mismo, la primera es de la web, y la otra
del dato de HA, no tengo el dato justo ahora de la EESS, pero se ve que al
menos son diferentes las que figuran en la web de las que da el "addon".

[image: image.png]

[image: image.png]

**Comment by MiguelAngelLV** [comment]
No se ven las fotos. Tienes que ponerlas directamente en Github, desde el email no se ven.

**Comment by ppnacho** [comment]
Pongo las fotos
![Captura de pantalla -2024-12-13 08-40-31](https://github.com/user-attachments/assets/618e73e7-d9e2-41de-91d1-682ea22694e5)
![image](https://github.com/user-attachments/assets/9edaef1e-e4ea-41a9-962c-b8e3dd9dadaa)

**Comment by MiguelAngelLV** [comment]
A mí me sale el mismo precio:

![image](https://github.com/user-attachments/assets/ac761f43-f697-46a9-9d5c-0be03460901d)


¿No habrás configurado algún tipo de descuento en la integración?

Despliega los atributos para que se muestre el precio original.

**Comment by ppnacho** [comment]
Arreglado, habia puesto un descuento fijo, lo que no se es si por defecto venia puesto y no lo quite, o lo fije yo por error. Gracias. Cierro el caso.
