### ISSUE TITLE
Manually Adjusting Update Interval for Gas Station Integration

### ISSUE THREAD

**Issue by kitopopo** [MiguelAngelLV/gas_station_spain#17]
Hello,

I would like to know in which file the update interval for this integration is defined. I have noticed that using another, more manual method for displaying gas station prices reflects changes much faster compared to this integration, which seems to have a longer refresh interval.

If possible, I would like to manually adjust the update interval to make it more frequent. Could you kindly point me to the specific file or the correct way to modify this parameter?

I am posting this as an issue since I couldn't find other communication channels, such as a discussion board, for this integration.

Thank you very much for creating this integration—it has been incredibly helpful in my Home Assistant setup. I truly appreciate the effort and time you’ve invested in developing it!

Best regards,

**Comment by MiguelAngelLV** [comment]
The update interval is 2 hours, it is defined here: https://github.com/MiguelAngelLV/gas_station_spain/blob/main/custom_components/gas_station_spain/const.py#L8

It is not a integration parameter.

The price change normally only once each day, so a a fastar changed I think it not necessary.

**Comment by MiguelAngelLV** [comment]
You can change manually the indicated line in your HA installation and check the behaviour

**Comment by kitopopo** [comment]
> You can change manually the indicated line in your HA installation and check the behaviour 

Thank you, you have been very kind and quick in responding. Thank you for your work and dedication.
