### ISSUE TITLE
Sugerencias de mejora - GNC y GLP

### ISSUE THREAD

**Issue by sergey08** [MiguelAngelLV/gas_station_spain#2]
Lo primero, gracias por el desarrollo.

Es muy cómodo poder crear entidades en Home Assistant de esta manera. Muchas gracias.

Como mejora, sugiero añadir el precio del GNC y GLP de las gasolineras.

Saludos

**Comment by MiguelAngelLV** [comment]
El problema es que no consigo conocer el ID de producto  de dichos combustibles.

Al hacer la llamada de una estación salen los nombres, pero necesito conocer el ID para poder filtrar previamente solo gasolineras que tengan dicho combustible.

**Comment by sergey08** [comment]
Hola Miguel Angel,

Por si te vale, yo hasta ahora obtengo el valor del precio del GNC con este código yaml.


  - scan_interval: 1800
    resource: https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/FiltroMunicipio/4384
    sensor:
      - name: "Pinto GNC"
        value_template: >-
          {% set station = value_json['ListaEESSPrecio'] | selectattr('IDEESS', 'match', '13781') | first %}
          {{ station['Precio Gas Natural Comprimido'] | replace(",",".") }}
        unit_of_measurement: "€/K"

**Comment by MiguelAngelLV** [comment]
Ahí directamente sacas el valor a partir del nombre, eso no habría problema sabiendo el nombre correcto de cada uno, pero para filtrar las gasolineras que tienen el tipo de combustible, necesito los IDs. Les he mandado varias veces un correo a los responsables de la API, pero ni caso.

Tampoco han arreglado lo de «Povincia»...

**Comment by MiguelAngelLV** [comment]
He conseguido los IDs a lo bruto (he hecho un mini programa que va probando números del 0 al 100...)

Ya tienes el update ;)
