### ISSUE TITLE
Integration within Carbu_com

### ISSUE THREAD

**Issue by myTselection** [MiguelAngelLV/gas_station_spain#3]
Hi, I see you have made a nice custom integration to get Spain gas station prices.
FYI, I've build something similar for different countries (BE/FR/LU/NL/DE/IT): https://github.com/myTselection/Carbu_com. I started with carbu.com site data, but extended it later on in order to support different countries.
Would it be ok for you if I'll try to integrate the Spanish gas station prices too in my Carbu_com integration?
So I'll take a look at the API you use to get it integrated...

Within my custom integration I also tried to build some services in order to allow the calculation of the cheapest gas station on a route.

**Comment by MiguelAngelLV** [comment]
Hi!

Not problem!.

 You can see the "lib"  in https://github.com/MiguelAngelLV/gas_station_spain/blob/main/custom_components/gas_station_spain/lib/gas_stations_api.py

The REST API is.. awful...  The government find the cheaper "developer"... So, only have a few endpoints with fix parameters.

If you have any question, ask ;)
