### ISSUE TITLE
Dar de alta todos los productos

### ISSUE THREAD

**Issue by cbolumar** [MiguelAngelLV/gas_station_spain#4]
Hola Miguel Angel , veo que estas aumentando la lista de productos pero no pones aun todos, podrías completarla salvo el hidrógeno que no encuentro ninguna hidrogenera.  Esta es la lista que tengo yo puesta en tu integración:

@staticmethod
async def get_products():
    return [
        Product(name="Gasolina 95 E5", id="1"),
        Product(name="Gasolina 98 E5", id="3"),
        Product(name="Gasóleo A", id="4"),
        Product(name="Gasóleo Premium", id="5"),
        Product(name="Gasóleo B", id="6"),
        Product(name="Gasóleo C", id="7"),
        Product(name="Biodiesel", id="8"),
        Product(name="Bioetanol", id="16"),
        Product(name="Gases licuados del petróleo", id="17"),
        Product(name="Gas natural comprimido", id="18"),
        Product(name="Gas natural licuado", id="19"),
        Product(name="Gasolina 95 E5 Premium ", id="20"),
        Product(name="Gasolina 98 E10", id="21"),
        Product(name="Gasolina 95 E10", id="23"),
    ]
Un saludo

**Comment by MiguelAngelLV** [comment]
Perfecto! la añado!

**Comment by cbolumar** [comment]
Muchas gracias
