### ISSUE TITLE
Propuesta de mejora

### ISSUE THREAD

**Issue by cbolumar** [MiguelAngelLV/gas_station_spain#5]
Ya puestos a pedir , creo que podrían añadírsele  2 campos mas en la entrada de datos especificando:  

**% de descuento
Céntimos de descuento**

Y si se rellenan aplicárselo al precio en el mismo sensor o en otro con precio neto .  Esto permitiría tener una ordenación personal por precio sin tener que hacérsela cada uno con ayudantes.

Un saludo

**Comment by MiguelAngelLV** [comment]
Esta la tenía pendiente de implementar, a ver si saco un hueco y me pongo con ello.

También tengo pendiente añadir las coordenadas.

**Comment by MiguelAngelLV** [comment]
He subido una beta con con los descuentos (fijos y/o con porcentaje).

En los atributos se mostrará el precio original sin descuento

También he añadido las opción de poder activar o no la visualización en el mapa.

Échale un ojo porfi ;)

**Comment by cbolumar** [comment]
La miro y te cuento, muchas gracias.
________________________________
De: Miguel Ángel López Vicente ***@***.***>
Enviado: sábado, 14 de octubre de 2023 08:06
Para: MiguelAngelLV/gas_station_spain ***@***.***>
Cc: cbolumar ***@***.***>; Author ***@***.***>
Asunto: Re: [MiguelAngelLV/gas_station_spain] Propuesta de mejora (Issue #5)


He subido una beta con con los descuentos (fijos y/o con porcentaje).

En los atributos se mostrará el precio original sin descuento

También he añadido las opción de poder activar o no la visualización en el mapa.

Échale un ojo porfi ;)

**Comment by cbolumar** [comment]
He probado la beta y funciona muy bien tanto descuentos como mapa, el precio original puede verse como atributo así que es utilizable si se necesita.

Muchas gracias, si veo alguna cosa con el uso , te la digo.

Un saludo
________________________________
De: Miguel Ángel López Vicente ***@***.***>
Enviado: sábado, 14 de octubre de 2023 08:06
Para: MiguelAngelLV/gas_station_spain ***@***.***>
Cc: cbolumar ***@***.***>; Author ***@***.***>
Asunto: Re: [MiguelAngelLV/gas_station_spain] Propuesta de mejora (Issue #5)


He subido una beta con con los descuentos (fijos y/o con porcentaje).

En los atributos se mostrará el precio original sin descuento

También he añadido las opción de poder activar o no la visualización en el mapa.

Échale un ojo porfi ;)

**Comment by MiguelAngelLV** [comment]
Me alegro, pues si a lo largo del finde no hace cosas raras lo pasaré a versión final.

PD: Me molesta MUCHO que el mapa principal del HA no tenga la opción de ocultar determinadas entidades...

**Comment by cbolumar** [comment]
Creo que cambiar el mapa lateral no es fácil, tendrás que hacerte otro, por ejemplo, con una pestaña de lovelace tipo panel.  puedes  intentar ponerlo en el menú lateral , no se si algo como esto te serviría:  https://community.home-assistant.io/t/configure-lovelace-cards-as-side-panels/167451/2
[https://community-assets.home-assistant.io/original/3X/8/0/80d3f33958a234aab5cb9364b998048064d12b9d.png]<https://community.home-assistant.io/t/configure-lovelace-cards-as-side-panels/167451/2>
Configure lovelace cards as side panels<https://community.home-assistant.io/t/configure-lovelace-cards-as-side-panels/167451/2>
I have a few input_booleans and input_numbers to configure things like when and if automations should run. It is nice to have them in the UI so I don’t have to change the config every time I would like to update the values. However, the frontend feels kind of cluttered when I add them, and usually I just end up with lots of tabs with configuration. Instead I would like to add them as different side panels (like HACS and configuration panel and such). Is there an easy way to create such a side pa...
community.home-assistant.io

________________________________
De: Miguel Ángel López Vicente ***@***.***>
Enviado: sábado, 14 de octubre de 2023 12:00
Para: MiguelAngelLV/gas_station_spain ***@***.***>
Cc: cbolumar ***@***.***>; Author ***@***.***>
Asunto: Re: [MiguelAngelLV/gas_station_spain] Propuesta de mejora (Issue #5)


Me alegro, pues si a lo largo del finde no hace cosas raras lo pasaré a versión final.

PD: Me molesta MUCHO que el mapa principal del HA no tenga la opción de ocultar determinadas entidades...

**Comment by bigramonk** [comment]
> Esta la tenía pendiente de implementar, a ver si saco un hueco y me pongo con ello.
> 
> También tengo pendiente añadir las coordenadas.

Genial, estaba a punto de pedirte agregar las coordenadas de la gasolinera al sensor :smile:
