### ISSUE TITLE
Algunas gasolineras han desaparecido

### ISSUE THREAD

**Issue by franlauma** [MiguelAngelLV/gas_station_spain#7]
Hola, en primer lugar agradecer tu trabajo ya que me esta ayudando para integrar algunas de mis gasolineras favoritas (antes tenía que hacerlo de forma manual).

Comentarte que con el nuevo año, algunas de estas gasolineras han desaparecido, ¿sabes donde puedo consultar la api con las gasolineras disponibles?

Un saludo y gracias.

**Comment by MiguelAngelLV** [comment]
En la descripción del proyecto, está el enlace a la API que ofrece el Gobierno con los datos: https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/help

Básicamente este componente consulta esa API. Sino están ahí...
